const BotEventType = {
  DIRECT_MESSAGE: "DIRECT_MESSAGE",
  MENTION: "MENTION",
  COMMAND: "COMMAND",
  KEYWORD_TRIGGER: "KEYWORD_TRIGGER",
  THREAD_REPLY: "THREAD_REPLY",
  BUTTON_CLICK: "BUTTON_CLICK",
  DROPDOWN_SELECTION: "DROPDOWN_SELECTION",
  MODAL_SUBMISSION: "MODAL_SUBMISSION",
  HELP_REQUEST: "HELP_REQUEST",
  INVALID_COMMAND: "INVALID_COMMAND",
  FALLBACK: "FALLBACK",
  ERROR: "ERROR",
  USER_JOIN: "USER_JOIN",
  USER_LEAVE: "USER_LEAVE",
  PERMISSION_CHANGE: "PERMISSION_CHANGE",
  SCHEDULED: "SCHEDULED",
  BACKLOGS_SCHEDULED: "BACKLOGS_SCHEDULED",
  NOTIFICATION: "NOTIFICATION"
};

module.exports = {
  BotEventType
};
